backend/urls.py
from django.urls import path
from backend.views.control import (
    bar_index,
    bar_marchant,
    bar_goods,
    bar_help,
    bar_forum,
    bar_order,
    bar_wallet,
    bar_user
)
from backend.views.index import b_index
from backend.views.marchant import (
    b_marchants_list,
    b_marchant_detail,
    b_marchant_flow,
    open_marchant_list,
    disable_marchant,
    enable_marchant,
    update_mct_settle,
    marchant_cmt_data
)
from backend.views.goods import (
    b_goods_detail,
    b_goods_list,
    disable_goods,
    enable_goods,
    b_goods_comment_list,
    b_goods_cat,
    create_bgoods_cat,
    update_bgoods_cat,
    delete_bgoods_cat,
    b_goods_state,
    create_bgoods_state,
    update_bgoods_state,
    delete_bgoods_state
)
from backend.views.order import (
    b_order_list,
    b_order_detail,
    order_adjust
)
from backend.views.forum import (
    b_forum_cat,
    create_bforum_cat,
    update_bforum_cat,
    delete_bforum_cat,
    b_forum_topic,
    create_bforum_topic,
    update_bforum_topic,
    delete_bforum_topic,
    b_forum_list,
    b_forum_detail,
    b_forum_comment,
    disable_forum,
    enable_forum
)
from backend.views.config import (
    mct_config_list,
    create_mct_config,
    update_mct_config
)
from backend.views.help_center import (
    bnews_list,
    bnews_detail,
    create_bnews,
    update_bnews,
    delete_news,
    bhd_list,
    bhd_detail,
    bhd_reply,
    bhd_close
)
from backend.views.wallet import (
    coin_list,
    create_coin,
    update_coin,
    delete_coin,
    wd_list,
    trans_list,
)

from backend.views.user import (
    user_list,
    user_detail,
    user_wallets,
    user_recv_address,
    user_collect_mct,
    user_collect_gds,
    user_backlist_mct,
    disable_user,
    enable_user
)
from backend.views.login import b_login, b_logout

urlpatterns = [
    # 侧边导航栏控制
    path(r"bar_index", bar_index, name="bar_index"),
    path(r"bar_marchant", bar_marchant, name="bar_marchant"),
    path(r"bar_goods", bar_goods, name="bar_goods"),
    path(r"bar_help", bar_help, name="bar_help"),
    path(r"bar_forum", bar_forum, name="bar_forum"),
    path(r"bar_order", bar_order, name="bar_order"),
    path(r"bar_wallet", bar_wallet, name="bar_wallet"),
    path(r"bar_user", bar_user, name="bar_user"),

    # 后台首页
    path(r"", b_index, name="b_index"),

    # 用户模块
    path(r"user_list", user_list, name="user_list"),
    path(r"<int:uid>/user_detail", user_detail, name="user_detail"),
    path(r"<int:uid>/user_wallets", user_wallets, name="user_wallets"),
    path(r"<int:uid>/user_recv_address", user_recv_address, name="user_recv_address"),
    path(r"<int:uid>/user_collect_mct", user_collect_mct, name="user_collect_mct"),
    path(r"<int:uid>/user_collect_gds", user_collect_gds, name="user_collect_gds"),
    path(r"<int:uid>/user_backlist_mct", user_backlist_mct, name="user_backlist_mct"),
    path(r"<int:uid>/disable_user", disable_user, name="disable_user"),
    path(r"<int:uid>/enable_user", enable_user, name="enable_user"),

    # 钱包模块
    path(r"coin_list", coin_list, name="coin_list"),
    path(r"create_coin", create_coin, name="create_coin"),
    path(r"<int:cid>/update_coin", update_coin, name="update_coin"),
    path(r"<int:cid>/delete_coin", delete_coin, name="delete_coin"),
    path(r"wd_list", wd_list, name="wd_list"),
    path(r"trans_list", trans_list, name="trans_list"),

    # 商家模块
    path(r"b_marchants_list", b_marchants_list, name="b_marchants_list"),
    path(r"<int:mid>/b_marchant_detail", b_marchant_detail, name="b_marchant_detail"),
    path(r"b_marchant_flow", b_marchant_flow, name="b_marchant_flow"),
    path(r"open_marchant_list", open_marchant_list, name="open_marchant_list"),
    path(r"<int:mid>/disable_marchant", disable_marchant, name="disable_marchant"),
    path(r"<int:mid>/enable_marchant", enable_marchant, name="enable_marchant"),
    path(r"<int:mid>/update_mct_settle", update_mct_settle, name="update_mct_settle"),
    path(r"<int:mid>/marchant_cmt_data", marchant_cmt_data, name="marchant_cmt_data"),

    # 商品模块
    path(r"b_goods_list", b_goods_list, name="b_goods_list"),
    path(r"<int:gid>/b_goods_detail", b_goods_detail, name="b_goods_detail"),
    path(r"<int:gid>/disable_goods", disable_goods, name="disable_goods"),
    path(r"<int:gid>/enable_goods", enable_goods, name="enable_goods"),
    path(r"<int:gid>/b_goods_comment_list", b_goods_comment_list, name="b_goods_comment_list"),
    path(r"b_goods_cat", b_goods_cat, name="b_goods_cat"),
    path(r"create_bgoods_cat", create_bgoods_cat, name="create_bgoods_cat"),
    path(r"<int:cid>/update_bgoods_cat", update_bgoods_cat, name="update_bgoods_cat"),
    path(r"<int:cid>/delete_bgoods_cat", delete_bgoods_cat, name="delete_bgoods_cat"),
    path(r"b_goods_state", b_goods_state, name="b_goods_state"),
    path(r"create_bgoods_state", create_bgoods_state, name="create_bgoods_state"),
    path(r"<int:sid>/update_bgoods_state", update_bgoods_state, name="update_bgoods_state"),
    path(r"<int:sid>/delete_bgoods_state", delete_bgoods_state, name="delete_bgoods_state"),

    # 订单模块
    path(r"b_order_list", b_order_list, name="b_order_list"),
    path(r"<int:oid>/b_order_detail", b_order_detail, name="b_order_detail"),
    path(r"<int:oid>/order_adjust", order_adjust, name="order_adjust"),

    # 论坛模块
    path(r"b_forum_cat", b_forum_cat, name="b_forum_cat"),
    path(r"create_bforum_cat", create_bforum_cat, name="create_bforum_cat"),
    path(r"<int:cid>/update_bforum_cat", update_bforum_cat, name="update_bforum_cat"),
    path(r"<int:cid>/delete_bforum_cat", delete_bforum_cat, name="delete_bforum_cat"),
    path(r"b_forum_topic", b_forum_topic, name="b_forum_topic"),
    path(r"create_bforum_topic", create_bforum_topic, name="create_bforum_topic"),
    path(r"<int:tid>/update_bforum_topic", update_bforum_topic, name="update_bforum_topic"),
    path(r"<int:tid>/delete_bforum_topic", delete_bforum_topic, name="delete_bforum_topic"),
    path(r"b_forum_list", b_forum_list, name="b_forum_list"),
    path(r"<int:fid>/b_forum_detail", b_forum_detail, name="b_forum_detail"),
    path(r"<int:fid>/b_forum_comment", b_forum_comment, name="b_forum_comment"),
    path(r"<int:fid>/disable_forum", disable_forum, name="disable_forum"),
    path(r"<int:fid>/enable_forum", enable_forum, name="enable_forum"),

    # 配置中心
    path(r"mct_config_list", mct_config_list, name="mct_config_list"),
    path(r"mct_config_list", mct_config_list, name="mct_config_list"),
    path(r"create_mct_config", create_mct_config, name="create_mct_config"),
    path(r"<int:cid>/update_mct_config", update_mct_config, name="update_mct_config"),

    # 帮助中心
    path(r"bnews_list", bnews_list, name="bnews_list"),
    path(r"create_bnews", create_bnews, name="create_bnews"),
    path(r"<int:nid>/bnews_detail", bnews_detail, name="bnews_detail"),
    path(r"<int:nid>/update_bnews", update_bnews, name="update_bnews"),
    path(r"<int:nid>/delete_news", delete_news, name="delete_news"),
    path(r"bhd_list", bhd_list, name="bhd_list"),
    path(r"<int:top_id>/bhd_detail", bhd_detail, name="bhd_detail"),
    path(r"bhd_reply", bhd_reply, name="bhd_reply"),
    path(r"<int:tid>/bhd_close", bhd_close, name="bhd_close"),

    # 登陆
    path(r"b_login", b_login, name="b_login"),
    path(r"b_logout", b_logout, name="b_logout"),
]

columbus/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("frontend.urls")),
    path("backend/", include("backend.urls")),
    path("captcha", include("captcha.urls")),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # 增加此行
]

clbauth/models.py
# encoding=utf-8

from django.db import models

from common.helpers import d0, dec
from common.models import (
    Asset,
    BaseModel,
    BoolYesOrNoSelect,
    DecField,
)

WithdrawDeposit = [
    (x, x) for x in ["Withdraw", "Deposit", "Transfer"]
]

TransWay = [
    (x, x) for x in ["Input", "Output"]
]

'''
Checking:    审核中(未锁定)
Trading:     交易中 
SendOut:     已发出 
Success:     成功 
Fail:        失败  
CheckPass:   审核通过 
CheckRefuse: 审核拒绝
'''
WalletStatus = [
    (x, x) for x in ["Checking", "Checked", "Trading", "SendOut", "Success", "Fail", "CheckPass", "CheckRefuse"]
]
'''
Input: 收入
Output: 支出
'''
TransRecordStatus = [
    (x, x) for x in ["Output", "Input"]
]

class AuthUser(BaseModel):
    user_name = models.CharField(
        max_length=100,
        default="columbos",
        verbose_name="用户名",
    )
    user_pho = models.ImageField(
        upload_to="user_img/%Y/%m/%d/",
        verbose_name="文章图片",
        blank=True,
        null=True,
    )
    password = models.CharField(
        max_length=100,
        default="",
        verbose_name="用户密码",
    )
    pin_code = models.CharField(
        max_length=100,
        default="",
        verbose_name="Pin码",
    )
    login_count = models.PositiveIntegerField(
        default=0,
        verbose_name="登陆次数"
    )
    token = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="用户token",
    )
    is_merchant = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",
        db_index=True,
        verbose_name="是不是商家",
    )
    member_level = models.PositiveIntegerField(
        default=0,
        verbose_name="登陆级别"
    )
    user_private_key = models.CharField(
        max_length=4096,
        default="",
        blank=True,
        null=True,
        verbose_name="私钥",
    )
    user_public_key = models.CharField(
        max_length=4096,
        default="",
        blank=True,
        null=True,
        verbose_name="公钥",
    )
    factor = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="Pin码",
    )
    is_open = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",
        db_index=True,
        verbose_name="是否开启2fa",
    )
    adjust_victor = models.PositiveIntegerField(
        default=0,
        verbose_name="调解胜利"
    )
    adjust_fail = models.PositiveIntegerField(
        default=0,
        verbose_name="调解失败"
    )
    active_time = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="活跃时间",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "用户表"
        verbose_name_plural = "用户表"

    def __str__(self):
        return self.user_name

    def as_dict(self):
        return {
            "id": self.id,
            "user_name": self.user_name,
        }


class UserWallet(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="user_wallet_rel",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    asset = models.ForeignKey(
        Asset,
        related_name="user_wallet_asset",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="资产",
    )
    chain_name = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="链名称",
    )
    pubkey = models.CharField(
        max_length=512,
        default="",
        blank=True,
        null=True,
        verbose_name="公钥",
    )
    privkey = models.CharField(
        max_length=512,
        default="",
        blank=True,
        null=True,
        verbose_name="私钥",
    )
    address = models.CharField(
        max_length=128,
        default="",
        blank=True,
        null=True,
        verbose_name="地址",
    )
    balance = DecField(
        default=d0,
        verbose_name="钱包余额"
    )
    in_amount = DecField(
        default=d0,
        verbose_name="钱包入账"
    )
    out_amount = DecField(
        default=d0,
        verbose_name="钱包出账"
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "用户钱包表"
        verbose_name_plural = "用户钱包表"

    def __str__(self):
        return self.address

    def as_dict(self):
        return {
            "id": self.id,
            "title": self.title,
        }


class WalletRecord(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="wallet_record_user",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    asset = models.ForeignKey(
        Asset,
        related_name="wallet_record_asset",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="资产",
    )
    chain_name = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="链名称",
    )
    from_addr = models.CharField(
        max_length=128,
        default="",
        blank=True,
        null=True,
        verbose_name="转出地址",
    )
    to_addr = models.CharField(
        max_length=128,
        default="",
        blank=True,
        null=True,
        verbose_name="转入地址",
    )
    amount = DecField(
        default=d0,
        verbose_name="转账金额"
    )
    tx_fee = DecField(
        default=d0,
        verbose_name="转账手续费"
    )
    tx_hash = models.CharField(
        max_length=128,
        default="",
        blank=True,
        null=True,
        verbose_name="交易Hash",
    )
    comment = models.CharField(
        max_length=128,
        default="",
        blank=True,
        null=True,
        verbose_name="备注",
    )
    w_or_d = models.CharField(
        max_length=100,
        choices=WithdrawDeposit,
        default="Withdraw",
        verbose_name="充值提现",
    )
    status = models.CharField(
        max_length=100,
        choices=WalletStatus,
        default="Checked",
        verbose_name="状态",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "钱包充值提现记录表"
        verbose_name_plural = "钱包充值提现记录表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}


class TansRecord(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="trans_relate_record_user",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    asset = models.ForeignKey(
        Asset,
        related_name="trans_relate_record_asset",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="资产",
    )
    amount = DecField(
        default=d0,
        verbose_name="金额"
    )
    trans_way = models.CharField(
        max_length=100,
        choices=TransWay,
        default="Input",
        verbose_name="收入支出",
    )
    source = models.CharField(
        max_length=1280,
        default="",
        blank=True,
        null=True,
        verbose_name="支付收入来源",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "钱包交易记录表"
        verbose_name_plural = "钱包交易记录表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}


class UserAddress(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="user_address_rel",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    user_name = models.CharField(
        max_length=100,
        default="columbos",
        blank=True,
        null=True,
        verbose_name="用户名",
    )
    phone = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="手机号码",
    )
    address = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="地址",
    )
    is_set = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",
        verbose_name="是不是默认地址",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "用户收货地址表"
        verbose_name_plural = "用户收货地址表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}


class UserDataStat(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="user_data_stat_rel",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    asset = models.ForeignKey(
        Asset,
        related_name="user_stat_asset",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="资产",
    )
    order_nums = DecField(
        default=d0,
        verbose_name="订单数量"
    )
    order_amount = DecField(
        default=d0,
        verbose_name="订单总计金额"
    )
    in_amount = DecField(
        default=d0,
        verbose_name="收入总计"
    )
    out_amount = DecField(
        default=d0,
        verbose_name="支出总计"
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "用户数据统计表"
        verbose_name_plural = "用户数据统计表"

    def as_dict(self):
        return {"id": self.id}

wallet/models.py
from django.db import models

# Create your models here.

wallet/views.py
from django.shortcuts import render

# Create your views here.

common/templates/front/wallet/wallet_deposit.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags%}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/balance.css' %}">
{% endblock %}
{% block body %}
<div class="layout-box">
   <ul class="breadcrumb-navigation-container">
      <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}"></a></li>
      <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}"></span>
      <div class="for-box">
        <li class="name-box">
          <a href="{% url 'index' %}" >充值</a>
        </li>
        <span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
      </div>
    </ul>
      <div class="account-balance-container">
        <div class="account-balance-left-container">
           <div class="detailed-list-2">
            <p class="module-title">钱包功能选项</p>
            <div class="detailed-list-2-content">
              {% include 'front/wallet/tab_box/wallet_tab.html' %}
            </div>
          </div>
          {% include 'front/public/list_item.html' %}
          {% include 'front/public/coin_rete.html' %}
        </div>
        <div class="account-balance-right-container">
          <div class="hint-text">
            <span></span>
            <img src="{% static 'images/jinggao.png' %}" alt="jinggao">
            <p>
              目前平台支持两种类型的虚拟币充值，优劣比对如下，您可自行选择合适的代币。
            </p>
          </div>
          <div class="hint-box">
            <p>ETH         隐私性一般   转账费高       购买简单    单价非常高</p>
            <p>TRC20-USDT  隐私性差     转账费非常便宜  购买简单    单价很低</p>
          </div>
          <div class="el-tabs" style="margin-top: 10px;">
            <div class="tabs-box">
              {% if asset == "ETH" %}
                  <a class="el-tab active" href="{% url 'wallet_deposit' %}?asset=ETH">ETH</a>
              {% else %}
                  <a class="el-tab" href="{% url 'wallet_deposit' %}?asset=ETH">ETH</a>
              {% endif %}
              {% if asset == "USDT" %}
                  <a class="el-tab active" href="{% url 'wallet_deposit' %}?asset=USDT">USDT</a>
              {% else %}
                  <a class="el-tab" href="{% url 'wallet_deposit' %}?asset=USDT">USDT</a>
              {% endif %}
            </div>
          </div>
          <div class="title-box">
            <p class="left-title">充值</p>
            <p class="right-title">
                <span>余额：{{ user_wallet.balance | keep_two_decimal_places }}</span>
            </p>
          </div>
          <div class="fund-content-box" style="display: block; text-align: center">
            <div><img style="width:300px; height:300px" src="{{ data_steam }}">
            <div class="code-box" style="text-align:center;">
                {{ user_wallet.address }}
            </div>
            <div style="margin-top: 10px; font-size:12px; color: red">
              <p>本地址只接收 {{ user_wallet.asset }} 充值，充值其他币种将不会到账</p>
              {% if asset == "ETH" %}
                <p>充值金额需要大于 0.001 ETH, 否则充值不会到账</p>
              {% else %}
                <p>充值金额需要大于 10 USDT, 否则充值不会到账</p>
              {% endif %}
            </div>
          </div>
          <hr/>
          <div class="pgp-box">
            <!-- <p class="pgp-title">获得PGP签署的所有权证明</p> -->
            {% if asset == "ETH" %}
            <p class="pgp-content">
              ● 该地址仅接受ETH，充错无法找回<br />
              ● 最小金额 0.001 ETH约为50美金左右，小于该金额会无法到账<br />
              ● 到账时间一般30分钟以内，如遇特殊情况（区块拥堵等）最迟1小时内到账<br />
              ● 超过一小时未到账可提交工单联系管理员<br />
              ● 具体到账可根据充值产生的交易ID到区块浏览器查看<br />
            </p>
            {% else %}
            <p class="pgp-content">
              ● 该地址仅接受 tron波场版本的USDT，协议TRC-20，非以太网络，充错无法找回<br />
              ● 最小金额 10 USDT，小于该金额会无法到账<br />
              ● 到账时间一般10分钟以内，如遇特殊情况（区块拥堵等）最迟1小时内到账<br />
              ● 超过一小时未到账可提交工单联系管理员<br />
              ● 具体到账可根据充值产生的交易ID到区块浏览器查看<br />
            </p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

common/templates/front/wallet/wallet_withdraw.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags%}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/balance.css' %}">
    <style>
        #id_amount, #id_asset {
            width: 100%;
            max-width: 450px;
            height: 40px;
            border: 1px solid #ddd;
            border-radius: 20px;
            padding: 0 15px;
            outline: none;
            font-size: 16px;
            line-height: 40px;
            box-sizing: border-box;
        }
    </style>
{% endblock %}
{% block body %}
<div class="layout-box">
   <ul class="breadcrumb-navigation-container">
      <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}"></a></li>
      <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}"></span>
      <div class="for-box">
        <li class="name-box">
          <a href="{% url 'index' %}" >首页</a>
        </li>
<span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
      </div>
    </ul>
      <div class="account-balance-container">
        <div class="account-balance-left-container">
           <div class="detailed-list-2">
            <p class="module-title">钱包功能选项</p>
            <div class="detailed-list-2-content">
             {% include "front/wallet/tab_box/wallet_tab.html" %}
            </div>
          </div>
          {% include 'front/public/list_item.html' %}
          {% include 'front/public/coin_rete.html' %}
        </div>
        <div class="account-balance-right-container">
          <div class="hint-text">
            <span></span>
            <img src="{% static 'images/jinggao.png' %}" alt="jinggao">
            <p>
              目前平台支持两种类型的虚拟币充值，优劣比对如下，您可自行选择合适的代币。
            </p>
          </div>
          <div class="hint-box">
            <p>ETH         隐私性一般   转账费高       购买简单    单价非常高</p>
            <p>TRC20-USDT  隐私性差     转账费非常便宜  购买简单    单价很低</p>
          </div>
          <div class="extract-box">
            <p class="extract-title">提现</p>
            <div class="extract-content">
              <p class="title">
                  <span>BTC余额: {{ user_btc_wallet.balance | keep_two_decimal_places }}</span>
                  <span style="margin-left:20px">USDT余额: {{ user_usdt_wallet.balance | keep_two_decimal_places }}</span>
              </p>
              <div class="form-box">
                <form method="post" action="{% url 'wallet_withdraw' %}">
                    <div class="el-form">
                      <div class="el-form-item">
                        <div class="el-form-label">币种</div>
                         {{ withdraw_form.asset }}
                         {% if withdraw_form.asset.errors %}
                             <div style="color:red; margin-left:8px; margin-top:5px">
                                 {{ withdraw_form.asset.errors }}
                             </div>
                         {% endif %}
                      </div>
                      <div class="el-form-item">
                        <div class="el-form-label">{{ user_wallet.asset.name }}地址</div>
                         {{ withdraw_form.address }}
                         {% if withdraw_form.address.errors %}
                             <div style="color:red; margin-left:8px; margin-top:5px">
                                 {{ withdraw_form.address.errors }}
                             </div>
                         {% endif %}
                      </div>
                      <div class="el-form-item">
                        <div class="el-form-label">金额</div>
                         {{ withdraw_form.amount }}
                         {% if withdraw_form.amount.errors %}
                             <div style="color:red; margin-left:8px; margin-top:5px">
                                 {{ withdraw_form.amount.errors }}
                             </div>
                         {% endif %}
                         {% if tip_msg %}
                             <div style="color:red; margin-left:8px; margin-top:5px">
                                {{ tip_msg }}
                             </div>
                         {% endif %}
                      </div>
                      <div class="el-form-item">
                        <div class="el-form-label">pin码</div>
                        {{ withdraw_form.pin_code }}
                         {% if withdraw_form.pin_code.errors %}
                             <div style="color:red; margin-left:8px; margin-top:5px">
                                 {{ withdraw_form.pin_code.errors }}
                             </div>
                         {% endif %}
                      </div>
                      {% if cipher_text_hex %}
                        <div class="el-form-item">
                           <textarea cols="40" rows="10" style="height:200px; width:560px;outline:none; padding:0; margin:0; box-sizing: border-box" >
                              {{ cipher_text_hex }}
                            </textarea>
                        </div>
                        <div class="el-form-item">
                            <div class="el-form-label">双重认证码</div>
                            {{ withdraw_form.factor }}
                             {% if withdraw_form.factor.errors %}
                                 <div style="color:red; margin-left:8px; margin-top:5px">
                                     {{ withdraw_form.factor.errors }}
                                 </div>
                             {% endif %}
                        </div>
                      {% endif %}
                      <div class="el-form-item">
                        <div class="el-form-label"></div>
                        <button type="submit" class="el-button primary send-btn">确认提取</button>
                      </div>
                    </div>
                </form>
              </div>
            </div>
             <div class="pgp-box">
                <p class="pgp-title">注意</p>
                <p class="pgp-content">提现地址需要填写正确，目前 USDT 只支持 TRC20-USDT提现，其他主链上不支持</p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}