backend/urls.py
from django.urls import path
from backend.views.control import (
    bar_index,
    bar_marchant,
    bar_goods,
    bar_help,
    bar_forum,
    bar_order,
    bar_wallet,
    bar_user
)
from backend.views.index import b_index
from backend.views.marchant import (
    b_marchants_list,
    b_marchant_detail,
    b_marchant_flow,
    open_marchant_list,
    disable_marchant,
    enable_marchant,
    update_mct_settle,
    marchant_cmt_data
)
from backend.views.goods import (
    b_goods_detail,
    b_goods_list,
    disable_goods,
    enable_goods,
    b_goods_comment_list,
    b_goods_cat,
    create_bgoods_cat,
    update_bgoods_cat,
    delete_bgoods_cat,
    b_goods_state,
    create_bgoods_state,
    update_bgoods_state,
    delete_bgoods_state
)
from backend.views.order import (
    b_order_list,
    b_order_detail,
    order_adjust
)
from backend.views.forum import (
    b_forum_cat,
    create_bforum_cat,
    update_bforum_cat,
    delete_bforum_cat,
    b_forum_topic,
    create_bforum_topic,
    update_bforum_topic,
    delete_bforum_topic,
    b_forum_list,
    b_forum_detail,
    b_forum_comment,
    disable_forum,
    enable_forum
)
from backend.views.config import (
    mct_config_list,
    create_mct_config,
    update_mct_config
)
from backend.views.help_center import (
    bnews_list,
    bnews_detail,
    create_bnews,
    update_bnews,
    delete_news,
    bhd_list,
    bhd_detail,
    bhd_reply,
    bhd_close
)
from backend.views.wallet import (
    coin_list,
    create_coin,
    update_coin,
    delete_coin,
    wd_list,
    trans_list,
)

from backend.views.user import (
    user_list,
    user_detail,
    user_wallets,
    user_recv_address,
    user_collect_mct,
    user_collect_gds,
    user_backlist_mct,
    disable_user,
    enable_user
)
from backend.views.login import b_login, b_logout

urlpatterns = [
    # 侧边导航栏控制
    path(r"bar_index", bar_index, name="bar_index"),
    path(r"bar_marchant", bar_marchant, name="bar_marchant"),
    path(r"bar_goods", bar_goods, name="bar_goods"),
    path(r"bar_help", bar_help, name="bar_help"),
    path(r"bar_forum", bar_forum, name="bar_forum"),
    path(r"bar_order", bar_order, name="bar_order"),
    path(r"bar_wallet", bar_wallet, name="bar_wallet"),
    path(r"bar_user", bar_user, name="bar_user"),

    # 后台首页
    path(r"", b_index, name="b_index"),

    # 用户模块
    path(r"user_list", user_list, name="user_list"),
    path(r"<int:uid>/user_detail", user_detail, name="user_detail"),
    path(r"<int:uid>/user_wallets", user_wallets, name="user_wallets"),
    path(r"<int:uid>/user_recv_address", user_recv_address, name="user_recv_address"),
    path(r"<int:uid>/user_collect_mct", user_collect_mct, name="user_collect_mct"),
    path(r"<int:uid>/user_collect_gds", user_collect_gds, name="user_collect_gds"),
    path(r"<int:uid>/user_backlist_mct", user_backlist_mct, name="user_backlist_mct"),
    path(r"<int:uid>/disable_user", disable_user, name="disable_user"),
    path(r"<int:uid>/enable_user", enable_user, name="enable_user"),

    # 钱包模块
    path(r"coin_list", coin_list, name="coin_list"),
    path(r"create_coin", create_coin, name="create_coin"),
    path(r"<int:cid>/update_coin", update_coin, name="update_coin"),
    path(r"<int:cid>/delete_coin", delete_coin, name="delete_coin"),
    path(r"wd_list", wd_list, name="wd_list"),
    path(r"trans_list", trans_list, name="trans_list"),

    # 商家模块
    path(r"b_marchants_list", b_marchants_list, name="b_marchants_list"),
    path(r"<int:mid>/b_marchant_detail", b_marchant_detail, name="b_marchant_detail"),
    path(r"b_marchant_flow", b_marchant_flow, name="b_marchant_flow"),
    path(r"open_marchant_list", open_marchant_list, name="open_marchant_list"),
    path(r"<int:mid>/disable_marchant", disable_marchant, name="disable_marchant"),
    path(r"<int:mid>/enable_marchant", enable_marchant, name="enable_marchant"),
    path(r"<int:mid>/update_mct_settle", update_mct_settle, name="update_mct_settle"),
    path(r"<int:mid>/marchant_cmt_data", marchant_cmt_data, name="marchant_cmt_data"),

    # 商品模块
    path(r"b_goods_list", b_goods_list, name="b_goods_list"),
    path(r"<int:gid>/b_goods_detail", b_goods_detail, name="b_goods_detail"),
    path(r"<int:gid>/disable_goods", disable_goods, name="disable_goods"),
    path(r"<int:gid>/enable_goods", enable_goods, name="enable_goods"),
    path(r"<int:gid>/b_goods_comment_list", b_goods_comment_list, name="b_goods_comment_list"),
    path(r"b_goods_cat", b_goods_cat, name="b_goods_cat"),
    path(r"create_bgoods_cat", create_bgoods_cat, name="create_bgoods_cat"),
    path(r"<int:cid>/update_bgoods_cat", update_bgoods_cat, name="update_bgoods_cat"),
    path(r"<int:cid>/delete_bgoods_cat", delete_bgoods_cat, name="delete_bgoods_cat"),
    path(r"b_goods_state", b_goods_state, name="b_goods_state"),
    path(r"create_bgoods_state", create_bgoods_state, name="create_bgoods_state"),
    path(r"<int:sid>/update_bgoods_state", update_bgoods_state, name="update_bgoods_state"),
    path(r"<int:sid>/delete_bgoods_state", delete_bgoods_state, name="delete_bgoods_state"),

    # 订单模块
    path(r"b_order_list", b_order_list, name="b_order_list"),
    path(r"<int:oid>/b_order_detail", b_order_detail, name="b_order_detail"),
    path(r"<int:oid>/order_adjust", order_adjust, name="order_adjust"),

    # 论坛模块
    path(r"b_forum_cat", b_forum_cat, name="b_forum_cat"),
    path(r"create_bforum_cat", create_bforum_cat, name="create_bforum_cat"),
    path(r"<int:cid>/update_bforum_cat", update_bforum_cat, name="update_bforum_cat"),
    path(r"<int:cid>/delete_bforum_cat", delete_bforum_cat, name="delete_bforum_cat"),
    path(r"b_forum_topic", b_forum_topic, name="b_forum_topic"),
    path(r"create_bforum_topic", create_bforum_topic, name="create_bforum_topic"),
    path(r"<int:tid>/update_bforum_topic", update_bforum_topic, name="update_bforum_topic"),
    path(r"<int:tid>/delete_bforum_topic", delete_bforum_topic, name="delete_bforum_topic"),
    path(r"b_forum_list", b_forum_list, name="b_forum_list"),
    path(r"<int:fid>/b_forum_detail", b_forum_detail, name="b_forum_detail"),
    path(r"<int:fid>/b_forum_comment", b_forum_comment, name="b_forum_comment"),
    path(r"<int:fid>/disable_forum", disable_forum, name="disable_forum"),
    path(r"<int:fid>/enable_forum", enable_forum, name="enable_forum"),

    # 配置中心
    path(r"mct_config_list", mct_config_list, name="mct_config_list"),
    path(r"mct_config_list", mct_config_list, name="mct_config_list"),
    path(r"create_mct_config", create_mct_config, name="create_mct_config"),
    path(r"<int:cid>/update_mct_config", update_mct_config, name="update_mct_config"),

    # 帮助中心
    path(r"bnews_list", bnews_list, name="bnews_list"),
    path(r"create_bnews", create_bnews, name="create_bnews"),
    path(r"<int:nid>/bnews_detail", bnews_detail, name="bnews_detail"),
    path(r"<int:nid>/update_bnews", update_bnews, name="update_bnews"),
    path(r"<int:nid>/delete_news", delete_news, name="delete_news"),
    path(r"bhd_list", bhd_list, name="bhd_list"),
    path(r"<int:top_id>/bhd_detail", bhd_detail, name="bhd_detail"),
    path(r"bhd_reply", bhd_reply, name="bhd_reply"),
    path(r"<int:tid>/bhd_close", bhd_close, name="bhd_close"),

    # 登陆
    path(r"b_login", b_login, name="b_login"),
    path(r"b_logout", b_logout, name="b_logout"),
]

columbus/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("frontend.urls")),
    path("backend/", include("backend.urls")),
    path("captcha", include("captcha.urls")),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # 增加此行
]

goods/models.py
# encoding=utf-8
from enum import Enum, unique

from django.db import models

from clbauth.models import AuthUser, UserAddress
from common.helpers import d0
from common.models import (
    Asset,
    BaseModel,
    BoolYesOrNoSelect,
    DecField,
)
from common.models import PayWaySelect
from marchant.models import Marchant

CalcWay = [(x, x) for x in ["件", "个", "斤"]]
ReturnExchange = [(x, x) for x in ["Return", "Exchange"]]


class GoodsCat(BaseModel):
    name = models.CharField(
        max_length=100,
        default="",
        verbose_name="分类名称",
    )
    is_active = models.BooleanField(
        default=True, verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商品分类表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def as_dict(self):
        return {
            "id": self.id,
            "user_name": self.name,
        }


class GoodsAttr(BaseModel):
    key = models.CharField(
        max_length=100,
        default="",
        verbose_name="属性Key",
    )
    value = models.CharField(
        max_length=100,
        default="",
        verbose_name="属性值",
    )
    is_active = models.BooleanField(
        default=True, verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商品属性表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.key

    def as_dict(self):
        return {
            "id": self.id,
            "user_name": self.key,
        }


class GoodsImage(BaseModel):
    image = models.ImageField(
        upload_to="goods_img/%Y/%m/%d/",
        verbose_name="商品图片",
        blank=True,
        null=True,
    )
    mark = models.CharField(
        max_length=100,
        default="",
        verbose_name="图标备注",
    )
    is_active = models.BooleanField(
        default=True, verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商品图片表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.image)

    def as_dict(self):
        return {
            "id": self.id,
            "user_name": self.mark,
        }


class GoodsSate(BaseModel):
    state = models.CharField(
        max_length=100,
        default="中国",
        verbose_name="产地名称",
    )
    is_active = models.BooleanField(
        default=True, verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商品产地表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.state

    def as_dict(self):
        return {
            "id": self.id,
            "state": self.state,
        }


class Goods(BaseModel):
    merchant = models.ForeignKey(
        Marchant,
        related_name="marchant_goods_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商家",
    )
    goods_cat = models.ForeignKey(
        GoodsCat,
        related_name="goods_cat",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商品分类",
    )
    goods_atrr = models.ManyToManyField(
        GoodsAttr,
        blank=True,
        null=True,
        verbose_name="商品属性",
    )
    goods_image = models.ManyToManyField(
        GoodsImage,
        blank=True,
        null=True,
        verbose_name="商品图片",
    )
    title = models.CharField(
        max_length=512,
        default="",
        verbose_name="商品标题",
    )
    goods_type = models.CharField(
        max_length=100,
        default="实体商品",
        verbose_name="商品类别",
    )
    name = models.CharField(
        max_length=512,
        default="",
        verbose_name="商品名称",
    )
    detail = models.CharField(
        max_length=512,
        default="",
        verbose_name="商品介绍",
    )
    logo = models.ForeignKey(
        GoodsImage,
        related_name="goods_logo_image",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商品LOGO"
    )
    mark = models.CharField(
        max_length=512,
        default="",
        verbose_name="商品备注",
    )
    serveice = models.CharField(
        max_length=512,
        default="",
        verbose_name="服务说明",
    )
    calc_way = models.CharField(
        max_length=100,
        choices=CalcWay,
        default="件",
        verbose_name="计量方式",
    )
    pay_way = models.CharField(
        max_length=100,
        choices=PayWaySelect,
        default="All",
        verbose_name="支持支付的方式",
    )
    origin_state = models.ForeignKey(
        GoodsSate,
        related_name="goods_origin_state",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商品产地",
    )
    total_amount = models.PositiveIntegerField(
        default=0, verbose_name="商品总量"
    )
    left_amount = models.PositiveIntegerField(
        default=100000, verbose_name="商品剩余量"
    )
    sell_nums = models.PositiveIntegerField(
        default=0, verbose_name="商品卖出量"
    )
    views = models.PositiveIntegerField(
        default=0, verbose_name="商品浏览次数"
    )
    return_goods_pc = models.CharField(
        max_length=1024,
        default="",
        verbose_name="退换货政策",
    )
    # 人民币价格
    price = DecField(
        default=d0, verbose_name="商品价格"
    )
    is_sale = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="Yes",
        verbose_name="商品上下架",
    )
    is_admin = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="Yes",
        verbose_name="商品是否代管",
    )
    is_active = models.BooleanField(
        default=True, verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商品表"
        verbose_name_plural = "商品表"

    def __str__(self):
        return self.name

    def as_dict(self):
        return {"id": self.id}


@unique
class OrderStatus(Enum):
    NO_PAY = "NO_PAY"                    # 未支付
    PAY_SUCCESS = "PAY_SUCCESS"          # 支付成功, 等待发货
    PAY_FAIL = "PAY_FAIL"                # 支付失败
    SEND_GOODS = "SEND_GOODS"            # 已发货, 等待收货
    RECV_GOODS = "RECV_GOODS"            # 已经收货, 等待评价
    RETURN_GOODS = "RETURN_GOODS"        # 退货换货
    FINISH = "FINISH"                    # 已完成
    PAYWAYUSDT = "PAYWAYUSDT"            # 支付的 USDT
    PAYWAYBTC = "PAYWAYBTC"              # 支付的 BTC


# 订单表
class GoodsOrder(BaseModel):
    list_status = [
        status for status in OrderStatus
    ]
    status_choices: list = [
        (status.value, status.value)
        for status in OrderStatus
    ]

    goods = models.ForeignKey(
        Goods,
        related_name="goods_order_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商品",
    )
    merchant = models.ForeignKey(
        Marchant,
        related_name="marchant_goods_order_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商家",
    )
    user_address = models.ForeignKey(
        UserAddress,
        related_name="recive_goods_address_relate",
        on_delete=models.CASCADE,
        default="",
        verbose_name="收货地址",
    )
    goods_atrr = models.ManyToManyField(
        GoodsAttr,
        blank=True,
        null=True,
        verbose_name="商品属性",
    )
    status = models.CharField(
        max_length=100,
        choices=status_choices,
        default="Unpay",
        verbose_name="订单状态",
    )
    goods_name = models.CharField(
        max_length=512,
        default="",
        verbose_name="商品名称",
    )
    cny_amount = DecField(
        default=d0, verbose_name="总支付的人民币"
    )
    goods_price = DecField(
        default=d0, verbose_name="商品价格"
    )
    asset_cny_price = DecField(
        default=d0, verbose_name="支付时币种的人民币价格"
    )
    goods_detail = models.CharField(
        max_length=512,
        default="",
        verbose_name="商品介绍",
    )
    logo =  models.ForeignKey(
        GoodsImage,
        related_name="goods_order_logo_image",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商品LOGO"
    )
    user = models.ForeignKey(
        AuthUser,
        related_name="buy_goods_user",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="购买商品的人",
    )
    buy_nums = models.PositiveIntegerField(
        default=1, verbose_name="购买数量"
    )
    pay_way = models.CharField(
        max_length=100,
        choices=PayWaySelect,
        default="件",
        verbose_name="计量方式",
    )
    pay_asset = models.ForeignKey(
        Asset,
        null=False,
        verbose_name="支付币种",
        on_delete=models.CASCADE,
    )
    pay_asset_cny_price = DecField(
        default=d0, verbose_name="支付时资产的人民币价格"
    )
    pay_coin_amount = DecField(
        default=d0, verbose_name="支付的币的数量"
    )
    order_number = models.CharField(
        max_length=512,
        default="",
        verbose_name="订单号",
    )
    logistics = models.CharField(
        max_length=512,
        default="",
        verbose_name="物流公司",
    )
    express_number = models.CharField(
        max_length=512,
        default="",
        verbose_name="快递运单号",
    )
    ret_logistics = models.CharField(
        max_length=512,
        default="",
        verbose_name="退货物流公司",
    )
    ret_ship_number = models.CharField(
        max_length=512,
        default="",
        verbose_name="退货运单号",
    )

    failure_reason = models.CharField(
        max_length=512,
        default="",
        verbose_name="失败原因",
    )
    pay_at = models.CharField(
        max_length=512,
        default="",
        verbose_name="支付时间",
    )
    deal_at = models.CharField(
        max_length=512,
        default="",
        verbose_name="处理时间",
    )
    is_cancle = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",
        verbose_name="是否退换货",
    )
    is_comment = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",

common/templates/front/goods/goods_collect_list.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags%}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/order_2.css' %}">
{% endblock %}
{% block body %}
 <div class="layout-box">
      <ul class="breadcrumb-navigation-container">
        <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}" alt="dingdan"></a>
        </li>
        <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}}"></span>
        <div class="for-box">
            <li class="name-box">
                <a href="#" >商品收藏</a>
            </li>
            <span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
        </div>
      </ul>
      <div class="collection-commodity-container">
        <div class="collection-commodity-left-container">
            {% include "front/public/list_item.html" %}
            {% include "front/public/coin_rete.html" %}
        </div>
        <div class="collection-commodity-right-container">
          <div class="title-box">
            <p class="title">商品收藏</p>
          </div>
          <ul class="commodity-list-box">
            {% for goods_clt in goods_clt_list %}
                <li>
                  <div class="left-commodity-box">
                    <a href="{% url 'goods_detail' goods_clt.goods.id %}">
                      <div class="img-box">
                        <img src="{% url 'enter_website' %}media/{{ goods_clt.goods.logo }}" alt="">
                      </div>
                      <div class="info-box">
                        <p class="name">{{ goods_clt.goods.title }}</p>
                        <p class="desc">{{ goods_clt.goods.name }}</p>
                        <p class="see-data"><span>浏览：{{ goods_clt.goods.views  }}</span><span>销售：{{ goods_clt.goods.sell_nums }}</span></p>
                        <p class="stock">剩余数量：{{ goods_clt.goods.left_amount }}</p>
                      </div>
                    </a>
                  </div>
                  <div class="right-commodity-box">
                    <p class="name">商品价格</p>
                    <p class="price">¥ {{ goods_clt.goods.price | keep_two_decimal_places }}</p>
                    <a href="{% url 'del_goods_collect' goods_clt.goods.id %}" class="el-button primary remove-btn">移除</a>
                  </div>
                </li>
            {% endfor %}
          </ul>
          {% include 'front/select/pagination.html' with items=goods_clt_list %}
        </div>
      </div>
    </div>
{% endblock %}

common/templates/front/goods/goods_detail.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/commodity.css' %}">
{% endblock %}
{% block body %}
    <div class="layout-box">
        <ul class="breadcrumb-navigation-container">
            <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}" alt="dingdan"></a>
            </li>
            <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}"></span>
            <div class="for-box">
                <li class="name-box">
                    <a href="#" >商品详情</a>
                </li>
                <span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
            </div>
        </ul>
        <div class="shop-detail-container">
            <div class="shop-detail-left-container">
                {% include "front/public/list_item.html" %}
                {% include "front/public/coin_rete.html" %}
            </div>
            <div class="shop-detail-right-container">
                <div class="shop-basic-info-box">
                    <div class="left-basic-info">
                        <div class="big-img-box">
                            <img src="{% url 'enter_website' %}media/{{ goods_detail.logo }}" alt="">
                        </div>
                        <ul class="small-img-box">
                            {% for goods_img in goods_detail.goods_image.all %}
                                <a href="{% url 'enter_website' %}media/{{ goods_img.image }}">
                                    <li>
                                        <img src="{% url 'enter_website' %}media/{{ goods_img.image }}" alt="">
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="right-basic-info">
                        <a style="text-decoration:none" href="{% url 'marchants_detail' goods_detail.merchant.id %}">
                            <span class="blue-text" style="margin-bottom:6px; font-size:18px">商家:{{ goods_detail.merchant }}</span>
                        </a>
                        <p class="shop-name"> {{ goods_detail.title }}</p>
                        <div class="desc">
                            <p>{{ goods_detail.goods_name }}</p>
                            <span class="blue-icon">供应商级别: {{ goods_detail.merchant.shop_level }}</span>
                            <span class="green-icon">信任级别: {{ request.session.member_level }}</span>
                        </div>
                        <p class="project-characteristic-title">产品特性</p>
                        <ul class="project-characteristic-content">
                            <li>
                                <div>
                                    <p>商品类型</p>
                                    <p class="gray-text">{{ goods_detail.goods_type }}</p>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <p>剩余量</p>
                                    <p class="gray-text">{{ goods_detail.left_amount }}</p>
                                </div>
                            </li>
                            {% if goods_detail.goods_type == "实体商品" %}
                                <li>
                                    <div>
                                        <p>商品类别</p>
                                        <p class="gray-text">{{ goods_detail.goods_cat }}</p>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <p>原产国</p>
                                        <p class="gray-text">{{ goods_detail.origin_state }}</p>
                                    </div>
                                </li>
                            {% endif %}
                            <li class="no-margin-bottom">
                                <div>
                                    <p>特殊说明</p>
                                    <p class="gray-text">{{ goods_detail.mark }}</p>
                                </div>
                            </li>
                        </ul>
                        <div class="price-box">
                            <p class="price">单价：<span>¥ {{ goods_detail.price | keep_two_decimal_places }}</span></p>
                            <p class="volume">已售：{{ goods_detail.sell_nums }}</p>
                        </div>
                        <form method="post" action="{% url 'pay_order_info' %}">
                            <div style="margin-bottom:30px">
                                <div class="buy-btn-box">
                                    <p class="balance-box" style="margin-right:30px; line-height:30px">
                                        {{ goods_eth_p }}eth/{{ goods_usdt_p }}usdt
                                    </p>
                                    <input type="hidden" name="eth_unit_coin_amount" value="{{ goods_eth_p }}">
                                    <input type="hidden" name="usdt_unit_coin_amount" value="{{ goods_usdt_p }}">
                                    <input type="number" name="goods_quantity" placeholder="请填写需要购买的商品数量" value="1" class="el-input__inner" style="width:100px; margin-right: 20px;">
                                    <select class="el-select" style="width:200px; height: 32px; margin-bottom:5px" name="pay_asset_name" required id="id_pay_way">
                                        <option value="Select" selected>请选择支付方式</option>
                                        <option value="ETH">ETH</option>
                                        <option value="USDT">USDT</option>
                                    </select>
                                </div>
                                <div class="buy-btn-box" style="display:inline-block">
                                    {% include 'front/select/select_address.html' %}
                                    <input type="hidden" name="goods_id" value="{{ goods_detail.id }}">
                                </div>
                                <div class="buy-btn-box">
                                     <button type="submit" class="buy-btn">立即购买</button>
                                     <a href="{% url 'goods_collect' goods_detail.id %}" class="buy-btn">收藏商品</a>
                                </div>
                            </div>
                            <div style="margin-bottom:10px; color: red; font-size:16px">
                                {{ tip_msg }}
                            </div>
                        </form>
                    </div>
                </div>
                <div class="el-tabs">
                    <div class="tabs-box">
                        {% if tab == 'goods' %}
                            <a class="el-tab active" href="{% url 'goods_detail'  goods_detail.id %}?tab=goods">商品描述</a>
                        {% else %}
                            <a class="el-tab" href="{% url 'goods_detail'  goods_detail.id %}?tab=goods">商品描述</a>
                        {% endif %}
                        {% if tab == "comment" %}
                            <a class="el-tab active" href="{% url 'goods_detail'  goods_detail.id %}?tab=comment">评价</a>
                        {% else %}
                            <a class="el-tab" href="{% url 'goods_detail'  goods_detail.id %}?tab=comment">评价</a>
                        {% endif %}
                        {% if tab == "return_p" %}
                            <a class="el-tab active" href="{% url 'goods_detail'  goods_detail.id %}?tab=return_p">退货政策</a>
                        {% else %}
                            <a class="el-tab" href="{% url 'goods_detail'  goods_detail.id %}?tab=return_p">退货政策</a>
                        {% endif %}
                    </div>
                </div>
                <div class="el-tab-content">
                    {% if tab == 'goods' %}
                        {{ goods_detail.detail }}
                    {% endif %}
                    {% if tab == 'comment' %}
                        <div class="comment-list-box">
                           {% for cmt in comment_list %}
                               <div class="comment-item">
                                  <div class="top-user-info">
                                    <div class="left-logo">
                                       {% if request.session.user_pho %}
                                            <img src="{% url 'enter_website' %}media/{{ request.session.user_pho }}" >
                                        {% else %}
                                            <img src="{% static 'images/touxiang_d.png' %}">
                                        {% endif %}
                                    </div>
                                    <div class="right-info-box">
                                      <p class="user-name">{{ cmt.user.user_name }}</p>
                                      <p class="time">{{ cmt.created_at | cn_hdatetime }}</p>
                                    </div>
                                  </div>
                                  <div class="content-box">{{ cmt.content }}</div>
                               </div>
                           {% endfor %}
                           {% include 'front/select/pagination.html' with items=comment_list %}
                        </div>
                    {% endif %}
                    {% if tab == 'return_p' %}
                         <div class="info-box">
                           {{ goods_detail.return_goods_pc }}
                          </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}