backend/urls.py
from django.urls import path
from backend.views.control import (
    bar_index,
    bar_marchant,
    bar_goods,
    bar_help,
    bar_forum,
    bar_order,
    bar_wallet,
    bar_user
)
from backend.views.index import b_index
from backend.views.marchant import (
    b_marchants_list,
    b_marchant_detail,
    b_marchant_flow,
    open_marchant_list,
    disable_marchant,
    enable_marchant,
    update_mct_settle,
    marchant_cmt_data
)
from backend.views.goods import (
    b_goods_detail,
    b_goods_list,
    disable_goods,
    enable_goods,
    b_goods_comment_list,
    b_goods_cat,
    create_bgoods_cat,
    update_bgoods_cat,
    delete_bgoods_cat,
    b_goods_state,
    create_bgoods_state,
    update_bgoods_state,
    delete_bgoods_state
)
from backend.views.order import (
    b_order_list,
    b_order_detail,
    order_adjust
)
from backend.views.forum import (
    b_forum_cat,
    create_bforum_cat,
    update_bforum_cat,
    delete_bforum_cat,
    b_forum_topic,
    create_bforum_topic,
    update_bforum_topic,
    delete_bforum_topic,
    b_forum_list,
    b_forum_detail,
    b_forum_comment,
    disable_forum,
    enable_forum
)
from backend.views.config import (
    mct_config_list,
    create_mct_config,
    update_mct_config
)
from backend.views.help_center import (
    bnews_list,
    bnews_detail,
    create_bnews,
    update_bnews,
    delete_news,
    bhd_list,
    bhd_detail,
    bhd_reply,
    bhd_close
)
from backend.views.wallet import (
    coin_list,
    create_coin,
    update_coin,
    delete_coin,
    wd_list,
    trans_list,
)

from backend.views.user import (
    user_list,
    user_detail,
    user_wallets,
    user_recv_address,
    user_collect_mct,
    user_collect_gds,
    user_backlist_mct,
    disable_user,
    enable_user
)
from backend.views.login import b_login, b_logout

urlpatterns = [
    # 侧边导航栏控制
    path(r"bar_index", bar_index, name="bar_index"),
    path(r"bar_marchant", bar_marchant, name="bar_marchant"),
    path(r"bar_goods", bar_goods, name="bar_goods"),
    path(r"bar_help", bar_help, name="bar_help"),
    path(r"bar_forum", bar_forum, name="bar_forum"),
    path(r"bar_order", bar_order, name="bar_order"),
    path(r"bar_wallet", bar_wallet, name="bar_wallet"),
    path(r"bar_user", bar_user, name="bar_user"),

    # 后台首页
    path(r"", b_index, name="b_index"),

    # 用户模块
    path(r"user_list", user_list, name="user_list"),
    path(r"<int:uid>/user_detail", user_detail, name="user_detail"),
    path(r"<int:uid>/user_wallets", user_wallets, name="user_wallets"),
    path(r"<int:uid>/user_recv_address", user_recv_address, name="user_recv_address"),
    path(r"<int:uid>/user_collect_mct", user_collect_mct, name="user_collect_mct"),
    path(r"<int:uid>/user_collect_gds", user_collect_gds, name="user_collect_gds"),
    path(r"<int:uid>/user_backlist_mct", user_backlist_mct, name="user_backlist_mct"),
    path(r"<int:uid>/disable_user", disable_user, name="disable_user"),
    path(r"<int:uid>/enable_user", enable_user, name="enable_user"),

    # 钱包模块
    path(r"coin_list", coin_list, name="coin_list"),
    path(r"create_coin", create_coin, name="create_coin"),
    path(r"<int:cid>/update_coin", update_coin, name="update_coin"),
    path(r"<int:cid>/delete_coin", delete_coin, name="delete_coin"),
    path(r"wd_list", wd_list, name="wd_list"),
    path(r"trans_list", trans_list, name="trans_list"),

    # 商家模块
    path(r"b_marchants_list", b_marchants_list, name="b_marchants_list"),
    path(r"<int:mid>/b_marchant_detail", b_marchant_detail, name="b_marchant_detail"),
    path(r"b_marchant_flow", b_marchant_flow, name="b_marchant_flow"),
    path(r"open_marchant_list", open_marchant_list, name="open_marchant_list"),
    path(r"<int:mid>/disable_marchant", disable_marchant, name="disable_marchant"),
    path(r"<int:mid>/enable_marchant", enable_marchant, name="enable_marchant"),
    path(r"<int:mid>/update_mct_settle", update_mct_settle, name="update_mct_settle"),
    path(r"<int:mid>/marchant_cmt_data", marchant_cmt_data, name="marchant_cmt_data"),

    # 商品模块
    path(r"b_goods_list", b_goods_list, name="b_goods_list"),
    path(r"<int:gid>/b_goods_detail", b_goods_detail, name="b_goods_detail"),
    path(r"<int:gid>/disable_goods", disable_goods, name="disable_goods"),
    path(r"<int:gid>/enable_goods", enable_goods, name="enable_goods"),
    path(r"<int:gid>/b_goods_comment_list", b_goods_comment_list, name="b_goods_comment_list"),
    path(r"b_goods_cat", b_goods_cat, name="b_goods_cat"),
    path(r"create_bgoods_cat", create_bgoods_cat, name="create_bgoods_cat"),
    path(r"<int:cid>/update_bgoods_cat", update_bgoods_cat, name="update_bgoods_cat"),
    path(r"<int:cid>/delete_bgoods_cat", delete_bgoods_cat, name="delete_bgoods_cat"),
    path(r"b_goods_state", b_goods_state, name="b_goods_state"),
    path(r"create_bgoods_state", create_bgoods_state, name="create_bgoods_state"),
    path(r"<int:sid>/update_bgoods_state", update_bgoods_state, name="update_bgoods_state"),
    path(r"<int:sid>/delete_bgoods_state", delete_bgoods_state, name="delete_bgoods_state"),

    # 订单模块
    path(r"b_order_list", b_order_list, name="b_order_list"),
    path(r"<int:oid>/b_order_detail", b_order_detail, name="b_order_detail"),
    path(r"<int:oid>/order_adjust", order_adjust, name="order_adjust"),

    # 论坛模块
    path(r"b_forum_cat", b_forum_cat, name="b_forum_cat"),
    path(r"create_bforum_cat", create_bforum_cat, name="create_bforum_cat"),
    path(r"<int:cid>/update_bforum_cat", update_bforum_cat, name="update_bforum_cat"),
    path(r"<int:cid>/delete_bforum_cat", delete_bforum_cat, name="delete_bforum_cat"),
    path(r"b_forum_topic", b_forum_topic, name="b_forum_topic"),
    path(r"create_bforum_topic", create_bforum_topic, name="create_bforum_topic"),
    path(r"<int:tid>/update_bforum_topic", update_bforum_topic, name="update_bforum_topic"),
    path(r"<int:tid>/delete_bforum_topic", delete_bforum_topic, name="delete_bforum_topic"),
    path(r"b_forum_list", b_forum_list, name="b_forum_list"),
    path(r"<int:fid>/b_forum_detail", b_forum_detail, name="b_forum_detail"),
    path(r"<int:fid>/b_forum_comment", b_forum_comment, name="b_forum_comment"),
    path(r"<int:fid>/disable_forum", disable_forum, name="disable_forum"),
    path(r"<int:fid>/enable_forum", enable_forum, name="enable_forum"),

    # 配置中心
    path(r"mct_config_list", mct_config_list, name="mct_config_list"),
    path(r"mct_config_list", mct_config_list, name="mct_config_list"),
    path(r"create_mct_config", create_mct_config, name="create_mct_config"),
    path(r"<int:cid>/update_mct_config", update_mct_config, name="update_mct_config"),

    # 帮助中心
    path(r"bnews_list", bnews_list, name="bnews_list"),
    path(r"create_bnews", create_bnews, name="create_bnews"),
    path(r"<int:nid>/bnews_detail", bnews_detail, name="bnews_detail"),
    path(r"<int:nid>/update_bnews", update_bnews, name="update_bnews"),
    path(r"<int:nid>/delete_news", delete_news, name="delete_news"),
    path(r"bhd_list", bhd_list, name="bhd_list"),
    path(r"<int:top_id>/bhd_detail", bhd_detail, name="bhd_detail"),
    path(r"bhd_reply", bhd_reply, name="bhd_reply"),
    path(r"<int:tid>/bhd_close", bhd_close, name="bhd_close"),

    # 登陆
    path(r"b_login", b_login, name="b_login"),
    path(r"b_logout", b_logout, name="b_logout"),
]

columbus/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("frontend.urls")),
    path("backend/", include("backend.urls")),
    path("captcha", include("captcha.urls")),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # 增加此行
]

marchant/models.py
# encoding=utf-8

from django.db import models

from clbauth.models import AuthUser
from common.helpers import d0
from common.models import (
    Asset,
    BaseModel,
    BoolYesOrNoSelect,
    DecField,
)
from common.models import PayWaySelect

MarchantConfigSelect = [
    (x, x) for x in ["Marchant", "Other"]
]


class Marchant(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="marchant_user_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    logo = models.ImageField(
        upload_to="marchant/%Y/%m/%d/",
        verbose_name="商家LOGO",
        blank=True,
        null=True,
    )
    name = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="商家名称",
    )
    introduce = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="商家介绍",
    )
    detail = models.CharField(
        max_length=1024,
        default="",
        blank=True,
        null=True,
        verbose_name="商家详细说明",
    )
    goods_num = models.PositiveIntegerField(
        default=0,
        verbose_name="商家商品个数"
    )
    settle_percent = DecField(
        default=d0,
        verbose_name="商家和平台结算比例"
    )
    shop_level = models.PositiveIntegerField(
        default=0,
        verbose_name="商家等级"
    )
    shop_score = models.CharField(
        max_length=100,
        default="0",
        blank=True,
        null=True,
        verbose_name="商家评分",
    )
    month_sell_num = models.PositiveIntegerField(
        default=0,
        verbose_name="本月销售量"
    )
    month_sell_amount = DecField(
        default=d0,
        verbose_name="本月销售金额"
    )
    total_sell_num = models.PositiveIntegerField(
        default=0,
        verbose_name="总销售量"
    )
    total_sell_amount = DecField(
        default=d0,
        verbose_name="总的销售金额"
    )
    adjust_victor = models.PositiveIntegerField(
        default=0,
        verbose_name="调解成功次数"
    )
    adjust_fail = models.PositiveIntegerField(
        default=0,
        verbose_name="调解失败次数"
    )
    is_active = models.BooleanField(
        default=True, verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商家表"
        verbose_name_plural = "商家表"

    def __str__(self):
        return self.name

    def as_dict(self):
        return {"id": self.id}


class MarchantCollect(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="marchant_collect_user",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    marchant = models.ForeignKey(
        Marchant,
        related_name="marchant_collect_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="收藏的商家",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商家收藏表"
        verbose_name_plural = "商家收藏表"

    def __str__(self):
        pass

    def as_dict(self):
        return {"id": self.id}


class MarchantConfig(BaseModel):
    btc_amount = DecField(
        default=d0,
        verbose_name="开通商家所需 BTC 个数"
    )
    eth_amount = DecField(
        default=d0,
        verbose_name="开通商家所需 ETH 个数"
    )
    usdt_amount = DecField(
        default=d0,
        verbose_name="开通商家所需 USDT 个数"
    )
    config_type = models.CharField(
        max_length=100,
        choices=MarchantConfigSelect,
        default="Marchant",
        blank=True,
        null=True,
        verbose_name="配置类别",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商家配置表"
        verbose_name_plural = "商家配置表"

    def as_dict(self):
        return {"id": self.id}


class MarchantOpenRecord(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="marchant_open_user_record_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    marchant = models.ForeignKey(
        Marchant,
        related_name="marchant_open_marchant",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="收藏的商家",
    )
    pay_coin_amount = DecField(
        default=d0,
        verbose_name="支付的币种数量"
    )
    pay_way = models.CharField(
        max_length=100,
        choices=PayWaySelect,
        default="BTC",
        blank=True,
        null=True,
        verbose_name="配置类别",
    )
    pay_at = models.CharField(
        max_length=100,
        default="",
        blank=True,
        null=True,
        verbose_name="支付时间",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "开通商家记录表"
        verbose_name_plural = "开通商家记录表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}


class MarchantOrderFlow(BaseModel):
    marchant = models.ForeignKey(
        Marchant,
        related_name="marchant_order_flow_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商家",
    )
    order_id = models.PositiveIntegerField(
        default=0,
        verbose_name="订单ID"
    )
    asset = models.ForeignKey(
        Asset,
        related_name="marchant_flow_asset_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="订单",
    )
    coin_amount = DecField(
        default=d0,
        verbose_name="币的数量"
    )
    is_valid = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",
        blank=True,
        null=True,
        verbose_name="是否有效数据",
    )
    is_stat = models.CharField(
        max_length=100,
        choices=BoolYesOrNoSelect,
        default="No",
        blank=True,
        null=True,
        verbose_name="是否已经统计",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否有效"
    )

    class Meta:
        verbose_name = "商家流水表"
        verbose_name_plural = "商家流水表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}


class MarchantStat(BaseModel):
    marchant = models.ForeignKey(
        Marchant,
        related_name="marchant_data_stat_mct",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="商家",
    )
    serice_best = models.PositiveIntegerField(
        default=0,
        verbose_name="服务好评"
    )
    service_good = models.PositiveIntegerField(
        default=0,
        verbose_name="服务中评"
    )
    service_bad = models.PositiveIntegerField(
        default=0,
        verbose_name="服务差评"
    )
    service_avg = DecField(
        default=d0,
        verbose_name="服务评论星率"
    )
    service_num = models.PositiveIntegerField(
        default=0,
        verbose_name="服务星星数量"
    )
    trade_best = models.PositiveIntegerField(
        default=0,
        verbose_name="交易好评"
    )
    trade_good = models.PositiveIntegerField(
        default=0,
        verbose_name="交易中评"
    )
    trade_bad = models.PositiveIntegerField(
        default=0,
        verbose_name="交易差评"
    )
    trade_avg = DecField(
        default=d0,
        verbose_name="交易评论星率"
    )
    trade_num = models.PositiveIntegerField(
        default=0,
        verbose_name="交易星星数量"
    )
    quality_best = models.PositiveIntegerField(
        default=0,
        verbose_name="质量好评"
    )
    quality_good = models.PositiveIntegerField(
        default=0,
        verbose_name="质量中评"
    )
    quality_bad = models.PositiveIntegerField(
        default=0,
        verbose_name="质量差评"
    )
    quality_avg = DecField(
        default=d0,
        verbose_name="质量评论星率"
    )
    quality_num = models.PositiveIntegerField(
        default=0,
        verbose_name="质量评论星星数量"
    )
    total_cmt_num = models.PositiveIntegerField(
        default=0,
        verbose_name="总评价星星数量"
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "商家数据统计表"
        verbose_name_plural = "商家数据统计表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}


class MarchantBackList(BaseModel):
    user = models.ForeignKey(
        AuthUser,
        related_name="marchant_blacklist_user",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="用户",
    )
    marchant = models.ForeignKey(
        Marchant,
        related_name="marchant_blacklist_mct_relate",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="黑名单商家",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="是否是有效"
    )

    class Meta:
        verbose_name = "屏蔽商家表"
        verbose_name_plural = "屏蔽商家表"

    def __str__(self):
        return ""

    def as_dict(self):
        return {"id": self.id}

marchant/forms/goods_file_form.py
# encoding=utf-8

import logging
from django import forms
from goods.models import GoodsImage


class GoodsFileForm(forms.ModelForm):
    image = forms.ImageField(
        required=True,
        error_messages={"invalid": "请输入上传商品图片, 商品图片不能为空"},
    )

    class Meta:
        model = GoodsImage
        fields = [
            'image'
        ]

    def __init__(self, request, *args, **kw):
        self.request = request
        super(GoodsFileForm, self).__init__(*args, **kw)

    def clean_image(self):
        image = self.cleaned_data.get('image')
        return image

    def save(self):
        super(GoodsFileForm, self).save(commit=True)

marchant/controller.py
# encoding=utf-8

common/templates/front/marchant/become_marchant.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/becomeSeller.css' %}">
{% endblock %}
{% block body %}
<div class="layout-box">
     <ul class="breadcrumb-navigation-container">
      <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}"></a></li>
      <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}"></span>
      <div class="for-box">
        <li class="name-box">
          <a href="{% url 'index' %}" >成为买家</a>
        </li>
        <span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
      </div>
    </ul>
      <div class="become-seller-container">
        <div class="become-seller-left-container">
           {% include 'front/public/list_item.html' %}
           {% include 'front/public/coin_rete.html' %}
        </div>
            <div class="become-seller-right-container">
              <p class="name-box">开通商家账户需知</p>
              <div class="info-box">
                <p>开通卖家账户必须遵守以下规则，点击同意按钮，支付相应的费用。</p>
                <p>注意：违反以下规则账户会被封禁。可在整改完成后重新申请开放。</p>
                <p>-----------------------------------------------------------</p>
                <p>#1：虚拟商品订单在24小时后自动完成，实物商品订单在7天后自动完成。</p>
                <p>#2：如果您收到太多投诉，我们可能会随时撤销您的卖家帐户。</p>
                <p>#3：开户费用100 USDT或等值 BTC</p>
                <p>#4：开通卖家身份前，所有卖家的个人资料中都必须有PGP公钥。</p>
                <p>#5：任何无端辱骂商家、买家的行为都可能会导致封号。</p>
                <p>#6：所有卖家账号都必须进行双因素认证（2FA）。</p>
                <p>#7：卖家必须在清单中准确描述其产品。如果我们发现虚假宣传，残次伪劣品销售，账号可能会被封禁。</p>
                <p>#8：不允许在平台之外进行交易。任何被发现之外私自交易的投诉，都会导致账号被封。</p>
                <p>#9：开户费用不做退还，一般面补贴平台开支，另外方面以此过滤掉一些不诚实的卖家。</p>
                <p>#10：点击下方的按钮开通商家默认已阅读并接受上述规定。</p>
              </div>
              <div style="color:red; font-size:16px; margin:20px"> {{ tip_msg }}</div>
              <div class="btn-box">
                {% if mct_config == None %}
                    {% include 'front/marchant/window/no_open.html' %}
                {% endif %}
                {% if balance == "NotEnough" %}
                    {% include 'front/marchant/window/to_deposit.html' %}
                {% endif %}
                {% if   open_marchant_req_way == "POST" %}
                    {% include 'front/marchant/window/mct_pay.html' %}
                {% endif %}
                    <a class="btn" href="{% url 'open_marchant' %}?pay_way=ETH" >支付 {{ mct_config.eth_amount | keep_two_decimal_places}} ETH</a>
                    <a class="btn" href="{% url 'open_marchant' %}?pay_way=USDT" >支付 {{ mct_config.usdt_amount | keep_two_decimal_places}} USDT</a>
                {% endif %}
              </div>
        </div>
    </div>
</div>
{% endblock %}

common/templates/front/marchant/marchant_add_info.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/seller_edit_info.css' %}">
    <style>
      #id_detail {
            border: 1px solid #ddd;
            border-radius: 20px;
      }
    </style>
{% endblock %}
{% block body %}
<div class="layout-box">
    <ul class="breadcrumb-navigation-container">
      <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}"></a></li>
      <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}"></span>
      <div class="for-box">
        <li class="name-box">
          <a href="{% url 'open_marchant' %}" >完善店铺信心</a>
        </li>
        <span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
      </div>
    </ul>
    <div class="become-seller-container">
      <div class="become-seller-left-container">
        {% include 'front/public/list_item.html' %}
         {% include 'front/public/coin_rete.html' %}
      </div>
      <div class="become-seller-right-container">
        <div class="title-box">
          <p class="title">完善店铺信息</p>
          <p class="more"></p>
        </div>
        <div class="form-box">
            <form method="post" action="{% url 'create_marchant' %}" enctype="multipart/form-data">
              <div class="el-form">
                <div class="el-form-item">
                  <div class="el-form-label">商家Logo</div>
                  <div class="el-upload">
                    <input type="hidden" name="pay_way" value="{{ pay_way }}">
                      {{ mct_open_form.logo }}
                       {% if mct_open_form.logo.errors %}
                         <div style="color:red; margin-left:8px; margin-top:5px">
                             {{ mct_open_form.logo.errors }}
                         </div>
                       {% endif %}
                  </div>
                </div>
                <div class="el-form-item">
                  <div class="el-form-label">商家名称</div>
                  {{ mct_open_form.name }}
                  {% if mct_open_form.name.errors %}
                    <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ mct_open_form.name.errors }}
                    </div>
                  {% endif %}
                </div>
                <div class="el-form-item">
                  <div class="el-form-label">商家简介</div>
                  {{ mct_open_form.introduce }}
                  {% if mct_open_form.introduce.errors %}
                    <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ mct_open_form.introduce.errors }}
                    </div>
                  {% endif %}
                </div>
                <div class="el-form-item">
                  <div class="el-form-label">商家详情</div>
                  {{ mct_open_form.detail }}
                  {% if mct_open_form.detail.errors %}
                    <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ mct_open_form.detail.errors }}
                    </div>
                  {% endif %}
                </div>
                <div class="el-form-item">
                    <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ tip_msg }}
                    </div>
                </div>
                <div class="el-form-item">
                  <div class="el-form-label"></div>
                  <button type="submit" class="el-button primary add-btn">确定</button>
                </div>
              </div>
            </form>
        </div>
      </div>
   </div>
</div>
{% endblock %}

common/templates/front/marchant/update_marchant.html
{% extends 'front/layout/main.html' %}
{% load staticfiles clb_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/seller_edit_info.css' %}">
    <style>
        #id_detail {
            border: 1px solid #ddd;
            border-radius: 20px;
       }
    </style>
{% endblock %}
{% block body %}
<div class="layout-box">
    <ul class="breadcrumb-navigation-container">
      <li class="icon-box"><a href="#" ><img src="{% static 'images/dingdan.png' %}"></a></li>
      <span class="lj-icon"><img src="{% static 'images/jt-1.png' %}"></span>
      <div class="for-box">
        <li class="name-box">
          <a href="{% url 'update_marchant'  marchant_detail.id  %}" >完善店铺信心</a>
        </li>
        <span class="lj-icon"><img src="{% static 'images/jt-2.png' %}"></span>
      </div>
    </ul>
    <div class="become-seller-container">
      <div class="become-seller-left-container">
        {% include 'front/public/list_item.html' %}
        {% include 'front/public/coin_rete.html' %}
      </div>
      <div class="become-seller-right-container">
        <div class="title-box">
          <p class="title">修改店铺信息</p>
          <p class="more"></p>
        </div>
        <div class="form-box">
            <form method="post" action="{% url 'update_marchant'  marchant_detail.id %}" enctype="multipart/form-data">
              <div class="el-form">
                  <div class="el-form-item">
                       <div class="el-form-label">商家Logo</div>
                      <input type="file" name="logo" accept="image/*" id="id_logo">
                  </div>
              </div>
              <div class="el-form">
                <div class="el-form-item">
                  <div class="el-form-label"></div>
                  <div class="el-upload">
                    <img width="180px" height="180px" src="{% url 'enter_website' %}media/{{ marchant_detail.logo }}">
                  </div>
                </div>
                <div class="el-form-item">
                  <div class="el-form-label">商家名称</div>
                  {{ marchant_form.name }}
                  {% if marchant_form.name.errors %}
                     <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ marchant_form.name.errors }}
                      </div>
                   {% endif %}
                </div>
                <div class="el-form-item">
                  <div class="el-form-label">商家简介</div>
                  {{ marchant_form.introduce }}
                  {% if marchant_form.introduce.errors %}
                     <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ marchant_form.introduce.errors }}
                      </div>
                   {% endif %}
                </div>
                <div class="el-form-item">
                  <div class="el-form-label">商家详情</div>
                  {{ marchant_form.detail }}
                   {% if marchant_form.detail.errors %}
                     <div style="color:red; margin-left:8px; margin-top:5px">
                        {{ marchant_form.detail.errors }}
                      </div>
                   {% endif %}
                </div>
                <div class="el-form-item">
                  <div class="el-form-label"></div>
                  <button type="submit" class="el-button primary add-btn">确定</button>
                </div>
              </div>
            </form>
        </div>
      </div>
   </div>
</div>
{% endblock %}